### ISSUE TITLE
maken van de vinyl overzicht

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#12]

**Comment by SamaraFellaDina** [comment]
![Image](https://github.com/user-attachments/assets/a06c654d-9414-4321-8300-a8b41c4e1e3d)

**Comment by wingsvn** [comment]
10.09.2024 breakdownschets
Ik heb een snelle breakdownschets gemaakt om voor mezelf duidelijk te krijgen welke elementen en gegevens ik nodig heb en hoe het album component in elkaar steekt. 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/d8f2291b-6d01-4240-85a7-46bbbbf598b5">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/990554c5-9850-4296-8691-e7cb5237272e">

Vervolgens heb ik een opzet gemaakt in sveltekit.
```
 <main>
    <h2>pick a track</h2>
    <ul>
      {#each data.persons as person}
        <li>
          <button class="vinyl-album">
            <img src={person.avatar} alt="{person.name}'s avatar" width="150" height="150" />
          </button>
          <div class="vinyl-record">
            <div class="vinyl-record-label">
            </div>
          </div>
        </li>
      {/each} 
    </ul>
  </main>
```

**Comment by wingsvn** [comment]
Hierna heb ik de de vinyl cover met de vinyl record samengevoegd:

```svelte
li {
    display: flex;
    flex-direction: row;
    align-items: center;
    list-style:"";
  }
```

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/3f32c687-56a0-4071-8363-191956aad447">
