### ISSUE TITLE
Het maken van de vinyl hover animatie

### ISSUE THREAD

**Issue by Ryank2004** [Hadil66/your-tribe-for-life-squad-page#17]

**Comment by Hadil66** [comment]
Eerst heb ik in CodePen de vinyl-hover-animatie uitgeprobeerd, terwijl Wing San nog bezig was met het design. Ik probeerde keyframes te gebruiken, maar daarbij rolde de vinyl niet terug bij het unhoveren en bleef hij na de animatie niet op zijn plaats. Daarom heb ik nu  `transform` en `transition `gebruikt.

> Codepen probeersel

![Image](https://github.com/user-attachments/assets/d8f40a7f-330d-483f-8c0a-61f0fa84c9c5)

> Uiteindelijke animatie
<img src="https://i.imgur.com/fAYOZTO.gif">
