### ISSUE TITLE
Maken van de info knop, waarin alle data staat

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#18]

**Comment by aliceafanasieva** [comment]
<h3>Referentie schets in Figma</h3>

<img width="931" alt="image" src="https://github.com/user-attachments/assets/f535366a-3299-4c8f-adcd-b5448d1fd46d">

<h3>Mijn code</h3>

**1. Info-knop toegevoegd:**
`  <button class="info-button" on:click={() => openPopup(48)}>i</button> `
Er is een ronde "info"-knop toegevoegd onderaan de pagina. Wanneer erop wordt geklikt, wordt de popup met data van een bepaalde gebruiker (nu nog alleen id=48 als test, omdat het nog samen moet worden gevoegd met andere code)  geopend, in de functie `openPopup(personId)`.

**2. Popup voor weergave van informatie:**
De popup toont een afbeelding (avatar), volledige naam, GitHub-handle en biografie van een persoon. De popup kan worden gesloten door op een kruisje te klikken in de rechterbovenhoek.

<img width="947" alt="image" src="https://github.com/user-attachments/assets/6ff37cff-7039-45b2-b81b-dd2ea74906f9">

**3. Data ophalen:**
Met een openPopup-functie wordt de informatie voor de gebruiker met bepaalde id opgehaald uit de data.persons en weergegeven in de popup.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/8a6678fb-a561-4020-a0d2-b41e8415940d">

**4. Stijl toegevoegd:**
<img width="448" alt="image" src="https://github.com/user-attachments/assets/9c69b6d6-7275-44d8-8eda-77e9daefd355"> 

**5. Mediaqueries:**
<img width="448" alt="image" src="https://github.com/user-attachments/assets/8c0cd5a4-7a6d-4e46-b060-27a8dc6f763b">

https://github.com/user-attachments/assets/d6550d45-b85d-413b-b365-37c85f4fb786
