### ISSUE TITLE
brainstormen ideeën squadpage

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#2]

**Comment by aliceafanasieva** [comment]
Mijn brainstorm:

![Image](https://github.com/user-attachments/assets/7e372fb8-41e1-4635-b39e-917fdb1d275e)


Mijn versie voor website design:

https://github.com/user-attachments/assets/5d23ac1a-4b2b-4a66-9b20-c189c756521c

**Comment by wingsvn** [comment]
Mijn ideeën voor de squadpage:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/20df75c2-0857-4e07-b3bc-34afb30f5ff9">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/449e86d6-0f22-4620-b64c-995c4e139fce">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/2127d64f-4383-49d2-9a62-1a1fdce1f643">

**Comment by Hadil66** [comment]
**Mijn ideeën:** 
![Schermafbeelding 2024-09-22 210338](https://github.com/user-attachments/assets/b3d1f8d6-a06c-4879-95ea-d4b8a3a69847)
![Schermafbeelding 2024-09-22 210447](https://github.com/user-attachments/assets/8aa675df-85e2-4d64-a6fd-38ede0821ec9)
<img src="https://i.imgur.com/6MFEGIq.png">
