### ISSUE TITLE
Functionaliteit van de persoon pop up maken

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#25]
Zorgen dat het functioneel is: 

- [x] dat de muziek shuffled 
- [x] dat je de popup krijgt met de audiocontrols, vinyl en naam van de persoon

![Image](https://github.com/user-attachments/assets/bf89bdce-5c46-4565-81e9-cf18178fe67b)

**Comment by lisagjh** [comment]
## 17 en 18 september

1. function: zorgen dat er een random nummer begint te spelen wanneer je op iemand klikt.

Nu de musicplayer op zich zelf werkt is de volgende stap om te zorgen dat er een random speelt als je op een persoon klikt.

Hiervoor moet er data gedeeld moeten kunnen worden tussen de main file (/src/route/+page.svelte) en het child component (src/lib/musicplayer).

De variable musicPlayerRef zal later naar de MusicPlayer refereren.

`bind:this={}` is een referentie naar het musicplayer component, waardoor de code uit dat component ook gebruikt kan worden in de main file.

Door de playPersonTrack() functie kan er een random nummer worden gespeeld, met het gebruik van de `playRandomSong()` functie in de musicplayer component.

Dus elke keer als je op een persoon klikt, word de `playPersonTrack()` functie aangeroepen, die dus weer de `playRandomSong()` functie van het musicplayer component aanroept.

```js
<script>
let musicPlayerRef;

  function playPersonTrack() {
    // Trigger the MusicPlayer to play a random song
    musicPlayerRef.playRandomSong();
  }
</script>

     ...
  <MusicPlayer bind:this={musicPlayerRef} />

```


`/lib/musicplayer`

Door in het component een `export {playRandomSong}` toe te voegen, kan deze functie in de main file gebruikt worden.

Ook heb ik de functie uitgebreid om er voor te zorgen dat er niet twee keer achter elkaar hetzelfde nummer word gespeeld. 

Dit werkt doordat het een index (getal) genereert, checkt of die hetzelfde is als het huidige/vorige nummer, en als dat het geval is genereert het een nieuwe, tot er een andere is.

```js
function playRandomSong() {
    // Pick a random song index that is different from the current one
    let randomIndex = Math.floor(Math.random() * playlist.length);

    // dont play the same song twice in a row
    while (randomIndex === songPlayingIndex) {
      randomIndex = Math.floor(Math.random() * playlist.length);
    }

    songPlayingIndex = randomIndex;
    play();
  }

  export { playRandomSong };
```

**Comment by lisagjh** [comment]
# 18.09

Volgende stap is zorgen dat er een dynamische component is. Hiervoor moet de data per persoon worden opgehaald, en ingeladen.

**Comment by lisagjh** [comment]
[commit](https://github.com/Hadil66/your-tribe-for-life-squad-page/commit/6c945c6737c6e6a20f392305399523ace0f211a4)

it works!! de styling moet nog gedaan worden maar komt goed :D 

Ik kom later teryg voor code uitleg

**Comment by lisagjh** [comment]
# 19.09

ik heb in de `lib` folder een file gemaakt genaamd `personDetail.svelte` .  Hier word de data per persoon opgehaald. 

```<script>
  export let personId = null;
  let person = null;

  // Fetch person details when the component is initialized or when personId changes
  $: if (personId) {
    fetchPersonDetails(personId);
  }

  async function fetchPersonDetails(id) {
    try {
      const url = `https://fdnd.directus.app/items/person/${id}`;
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error("Failed to fetch person data");
      }
      const json = await response.json();
      person = json.data;
    } catch (error) {
      console.error(error);
      person = null; // Handle errors (e.g., show a message)
    }
  }
</script>

{#if person}
  <div class="person-detail">
    <h2>{person.name}</h2>
    <p>{person.bio}</p>
    <!-- Add more details about the person here -->
  </div>
{:else if personId}
  <p>Loading person details...</p>
{/if}
```

in de main `+page.svelte` heb ik de functie die eerst alleen de muziek speelde vervangen door een functie waar meerdere dingen inzitten, zo selecteert het die id, word de "pop up" geopend en speelt het een nummer

```
// Combined function to play music and show person details
  function handlePersonClick(id) {
    selectedPersonId = id;
    playPersonTrack();
  }
```



Ook is er een functie om de pop up te sluiten, en de muziek te stoppen
```
  // Combined function to play music and show person details
  function handlePersonClick(id) {
    selectedPersonId = id;
    musicPlayerRef.playRandomSong(); 
  }
```

Dit is de popup, waar het component met de persoonsgegevens word in geladen.
```
{#if selectedPersonId}
    <!-- Correctly pass the personId prop to PersonDetail -->
    <div class="slide-in slide-in-active">
      <PersonDetail personId={selectedPersonId} />
      <button class="close-btn" on:click={closePersonDetail}>Close</button>
    </div>
    <MusicPlayer bind:this={musicPlayerRef} />
  {/if}
```

**Comment by lisagjh** [comment]
# 19.09

[commit](https://github.com/Hadil66/your-tribe-for-life-squad-page/commit/669742dc92d6b3f26b6cd0ecd022c68bfc2a6876)

De recordplayer van Hadil samen gevoegd met mijn dingetjes en nu werkt het!!!

#### next

- [ ] zorgen dat de popup juist ingedeeld is (naast elkaar ipv boven elkaar)
- [ ] styling van het component verder

**Comment by lisagjh** [comment]
# 20.09

Begin van de styling is er!

Ik krijg de popup alleen niet in het midden om een of ander reden :( het werkt niet mee

![Image](https://github.com/user-attachments/assets/3f42b854-4405-44a4-ae01-360147741c4c)
