### ISSUE TITLE
Hoe gaan wij alles mergen?

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#26]

**Comment by lisagjh** [comment]
Vrijdag 13-09 alle PRs van wat we hebben maken, mergen en samen de conflicten op lossen.

**Comment by Hadil66** [comment]
Vrijdag 20 september 12:30

**Comment by Hadil66** [comment]
Alles gemerged!

Zie [hier](https://github.com/Hadil66/your-tribe-for-life-squad-page/commits/main/)
