### ISSUE TITLE
`li` elementen een achtergrond geven

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#63]
![image](https://github.com/user-attachments/assets/641c634d-59ed-463b-a55f-fe692dc22509)

Sommige `li` elementen bevatten een `img` die doorzichtig is, waardoor de achtergrond zichtbaar word en de lp. Het is dus handig om hieraan een achtergrond mee te geven

**Comment by Hadil66** [comment]
Dit ook aanpassen

![Image](https://github.com/user-attachments/assets/6a604a9c-7995-4999-bfea-fed27b2a0d16)
