### ISSUE TITLE
`li` element een `width` en een `height` meegeven

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#64]
![image](https://github.com/user-attachments/assets/e8685a5a-3f09-4960-80da-db834305bf15)

Wanneer een foto niet word ingeladen, veranderd het grid. Misschien fijn als dit al een `width` en een `height` meekrijgt

**Comment by wingsvn** [comment]
Ik heb dit aangepast:
li {
    display: flex;
    flex-direction: row;
    align-items: center;
    list-style:"";
    position: relative;
    **width: 6em;
    height: 8em;**
  }
<img width="250" alt="Scherm­afbeelding 2024-09-19 om 15 47 23" src="https://github.com/user-attachments/assets/bf5292d1-4646-4f37-b3f1-fcd98b6bcf41">
