### ISSUE TITLE
Kampvuursessie

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#73]
Hier een template wat je kan gebruiken om het te documenteren
# Hoe ging de samenwerking?

**Comment by SamaraFellaDina** [comment]
# Hoe ging de samenwerking?

## Wat heb je ervan geleerd, wat neem je mee?
* Ik heb meer geleerd over het samenwerken binnen een project board
 * Werken met planning poker
 * Werken met MoSCoW
 * Werken met assigned issues
 * Werken met Labels

Ik heb de samenwerking goed ervaren, wij zijn erg eerlijk in hoe de communicatie is gegaan. We hebben allemaal eerlijk kunnen vermelden wat we van de samenwerking vinden en eventueel ook eigen minpunten te beschrijven

### Welke minpunten heb jij bij jezelf gezien bij de samenwerking?
* Ik kan soms te diep in gaan op een issue in plaats van dat ik mijn taken meer verdeel
* Ik ben soms geneigd om enige structuur en leiding te bieden, in plaats van dat ik andere ook aan het woord laat
* Ik mag andere ook aanmoedigen om werk (zoals een projectboard maken) uit te voeren, in plaats van datik het zelf meteen doe.
* when.

### Wat ging er goed?
* Goede communicatie, je merkt dat we allemaal op een lijn zitten als het gaat om
  * coderen
  * samenwerking
  * ambitie
* Er is duidelijk gecommuniceerd wat betreft branches en pull request, waarbij we elkaar op de hoogte hielden wanneer we een push naar de main deden. Of gewoon een update geven over een issue

### Wat kan er beter?
* Tijdens het start van het project hadden we sneller een soort skelet bestand kunnen maken waarin we enchantement code konden toepassen. 
  * In de eerste week zijn we veel aan verschillende issues gaan werken, zonder een template bestand te hebben waarop we alles konden basseren
  * Het duurde een week tot we iets live konden zetten, dat zou voor een volgende keer meer een prioriteit moeten zijn. 

## Wat heb ik zelf nodig voor een goede samenwerking?
* Motivatie van anderen, zodat er initiatief vanuit meerdere kanten komt. Daardoor word een project belangrijk en hoef je niet achter andermans verantwoording aan
* Eerlijkheid, reeel blijven, waarin je eerlijk met je team doelen en issues kan delen zonder dat dit persoonlijk word opgepakt
* Documentatie in het projectboard. Dat het team verantwoording toont voor eigen issues binnen het projectboard, zodat er een duidelijk documentatie en structuur blijft
* Elkaar durft aan te spreken mits nodig. Het is nodig om elkaar te kunnen aanspreken mits je hulp nodig hebt of opmerkingen, taken, issues en meer kan benoemen en een ander durft te herrinneren eraan. Dit betekent ook dat teamleden kritisch durven te zijn, waarin je anderen motiveert om het serieus te nemen en/of ergens aan te herrineren
* Verantwooring voor eigen presentie, afspraken en taken. Teamleden tonen eigen verantwoording voor wanneer ze niet aanwezig zijn, iets niet lukt of eerlijk zijn met het werk wat ze hebben gemaakt (of juist niet hebben gemaakt)

**Comment by lisagjh** [comment]
# Hoe ging de samenwerking?

## Wat heb je ervan geleerd, wat neem je mee?

Ik heb geleerd om beter in een team samen te werken, door het werken met een projectboard, mergen van code, en verantwoordelijkheid voor mijn eigen taken.

### Wat ging er goed?

Ik vond dat de taakverdeling erg goed ging. Iedereen pakte snel iets op en deed dit ook echt.

Ook hield vrijwel iedereen elkaar goed up to date door middel van documentatie in een issue of updates via teams. En iedereen hield zich aan de afspraken die we maakte, zoals teams meetings.

Voor een eerste keer planning poker ging dat ook goed, en zagen we er ook allemaal wel het nut er van in. Niet alleen om te schatten hoeveel tijd een taak kost, maar ook om met elkaar in gesprek te gaan over de taak en te horen hoe anderen het zouden aanpakken of bouwen of er moeilijk aan vinden.


### Wat kan er beter?

We hadden beter overdraagbare code kunnen schrijven. Het was nu allemaal vrij chaotisch en onoverzichtelijk.


### Wat kan ik beter doen?

Betere en duidelijkere code schrijven. Ik heb het gevoel dat de code die ik nu heb geschreven niet echt geweldig is, maar meer een "if it works, it works" idee heeft. 

Ook is het erg slecht overdraagbaar. Ik had er meer comments met uitleg in moeten zetten om het duidelijker te maken. Ook vind ik dat het erg onoverzichtelijk heb gemaakt. 


## Wat heb ik zelf nodig voor een goede samenwerking?

Ik houd van duidelijkheid <3 hoe duidelijker hoe beter. Dus een projectboard zoals wij hebben gebruikt vind ik erg fijn. Het is overzichtelijk. Het is duidelijk. je kan zien wie wat doet en hoever diegene is. 


###### was gezellig :)

**Comment by aliceafanasieva** [comment]
<h1>Hoe ging de samenwerking?</h1>

<h2>Wat heb je ervan geleerd, wat neem je mee?</h2>
Bij samenwerking tijdens deze sprint het ik erg veel geleerd, aangezien ik vorig jaar ook niet vaak in een groep heb samengewerkt. Ik moest leren hoe ik moet werken met branches, hoe ik moet mergen, pushen etc. 
Ik heb ook veel geleerd over projectboard en issues, hoe je issues uit projectboard kan opnemen met assignees, hoe je issues sorteert met milestones en labels. 

<h2>Wat ging er goed?</h2>
Ik vind dat het in het algemeen wel goed ging, communicatie ging soepel, iedereen was goed betrokken. Ik zag ook dat mijn groepsgenoten goed bezigwaren met hun taken (issues) en ook graag gingen helpen als er iets mis ging. 

<h2>Wat kan er beter?</h2>
Ik denk dat de planning volgende keer wel beter kan, ik persoonlijk moet ook veel beter mijn tijd leren verdelen, en mijn capaciteit goed kennen, zodat ik beter weet hoeveel tijd iets mij gaat kosten om te doen. Ik heb de tijd niet zo goed ingeschat, ik moest zelf wel wat meer tijd hebben om te kijken hoe veel dingen werken, had moeilijkheid met werken met Github en moest meer tijd nemen om te kijken hoe precies Sveltekit werkt. Ook denk ik dat ik nog niet helemaal ben ingestroomd van de zomer, ik moet weer mezelf discipleneren om de werktempo weer goed te zetten. 

<h2>Wat heb ik zelf nodig voor een goede samenwerking?</h2>

- Ik moet meer vragen stellen aan de rest van mijn team als ik weet, dat er iets niet lukt of sneller als ik een fout tegenkom. 
- Ik moet beter leren plannen, en beter inschatten hoe ik de issue aanpak en hoeveel tijd ik hiervoor nodig heb. 
- Meer tijd besteden aan het bestuderen van theorie, want daar had ook slecht voor gepland.

**Comment by wingsvn** [comment]
**Hoe ging de samenwerking?**
De samenwerking vond ik heel fijn gaan. We hebben gewerkt met een projectboard en hierin issues aangemaakt en deze issues verdeelt via assignees. De communicatie was ook fijn. We konden elkaar bereiken via teams en hebben ook balmomenten gehad.

**Wat heb je ervan geleerd, wat neem je mee?**
Tijdens deze samenwerking heb ik met nieuwe samenwerkingsmethoden gewerkt. Namelijk een uitgebreidere manier van het werken met de projectboard. We hebben veel gebruik gemaakt van labels. Dit gaf structuur en duidelijkheid, aangezien we met een groot team werkten. Andere dingen waar we deze sprint mee hebben gewerkt zijn planning poker en MoSCoW. Dit is ook iets wat ik mee wil nemen de volgende keer om de tijd en de moeilijkheidsgraad beter in te schatten.

**wat ging er goed?**
De taakverdeling is goed gegaan. Iedereen pakte uit zichzelf een taak op als die al klaar was. Door het gebruik van comments en statussen binnen onze projectboard en issues, was het duidelijk hoe ver we in ons proces waren.

**wat kan er beter?**
We begonnen in het begin goed met deadlines en afspraken, maar dit verwaterde al snel. Voor een volgende keer is het fijn als we ons hier aan kunnen houden, zodat er meer duidelijkheid is over de planning. 


**Wat heb ik zelf nodig voor een goede samenwerking?**
Duidelijke code uitleg/documentatie, zodat ik de code van anderen kan begrijpen en hiermee verder kan werken of merge conflicts makkelijker kan oplossen.

**Comment by Hadil66** [comment]
# Hoe ging de samenwerking?
De samenwerking ging best wel goed we hielden elkaar vaak op de hoogte met wat we aan het doen waren. Tegen het eind kwamen we wel een beetje in tijdsnoot. 

## Wat heb je ervan geleerd, wat neem je mee?
- Het gebruiken van een projectboard op deze manier en mijn documentatie in de comments te schrijven.
- Het werken met een planning poker, hierdoor hebben we een beter inzicht gekregen in de moeilijkheidsgraad en de geschatte duur van elke taak.

## Welke minpunten heb jij bij jezelf gezien bij de samenwerking?
Ik stel liever zo min mogelijk vragen en probeer het graag zelf. Dit werkte in mijn nadeel, omdat ik uiteindelijk veel langer bezig was met een onderdeel dat ik veel sneller af had kunnen hebben.

### Wat ging er goed?
De taakverdeling en planning poker ging goed. Ik heb zo een beter grip heb gekregen op de moeitegraad van de taken. 
### Wat kan er beter?

## Wat heb ik zelf nodig voor een goede samenwerking?
Focus meer op één ding tegelijk en minder multitasken.  Het gebruik van een projectboard, zoals we hier hebben gedaan. Het is veel overzichtelijker en handig in gebruik.
