### ISSUE TITLE
Breakdown schets maken

### ISSUE THREAD

**Issue by SamaraFellaDina** [Hadil66/your-tribe-for-life-squad-page#9]

**Comment by lisagjh** [comment]
Dit is de breakdown geworden. Hij is te vinden in [figma](https://www.figma.com/design/OflVytM5nOBvvCE0EkUer5/Squadpage?node-id=63-26&t=rN200FLL7zPzxsJk-1).

@team als er iets mist laat het me weten! 

![Image](https://github.com/user-attachments/assets/a7abc6c9-94ab-487e-8f05-f4732e6cc0af)
